name: Dependabot .NET Restore Fix

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 1 * *' # Jalan setiap tanggal 1 bulan baru

jobs:
  check-maui-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Install MAUI Workload
        run: dotnet workload install maui-android

      - name: Restore Project
        run: dotnet restore ./AumoFinance.csproj
