<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net9.0-android;net9.0-ios</TargetFrameworks>
		<OutputType>Exe</OutputType>
		<RootNamespace>AumoFinance</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>

		<!-- Pastikan MauiXamlInflator bernilai false atau dihapus -->
		<MauiXamlInflator>false</MauiXamlInflator>
	</PropertyGroup>

	<ItemGroup>
		<!-- Tambahkan Package Fingerprint disini -->
		<PackageReference Include="Plugin.Fingerprint" Version="3.0.0-beta.1" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
	</ItemGroup>

</Project>
