name: Copy Secrets to Target Repo

on:
  workflow_dispatch:

jobs:
  copy-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Secrets to Target Repo
        uses: jaredfrayer/copy-secrets-action@v1.0.0
        with:
          target_repo: 'rdmmoonlight/aumo-mobile'
          github_token: ${{ secrets.TARGET_REPO_PAT }}
          secrets: |
            ANDROID_KEYSTORE_BASE64
            ANDROID_KEYSTORE_PASSWORD
            ANDROID_KEY_ALIAS
            ANDROID_KEY_PASSWORD
            PAT_TOKEN
            
