name: NuGet Dependency Check

on:
  schedule:
    - cron: '0 2 * * 1' # Berjalan setiap hari Senin jam 02:00
  workflow_dispatch:

jobs:
  restore-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Install .NET MAUI & Android Workloads
        run: |
          dotnet workload update
          dotnet workload install maui-android

      - name: Restore Project Successfully
        run: dotnet restore ./AumoFinance.csproj
