name: NuGet Dependency Check & Update

on:
  schedule:
    - cron: '0 2 * * 1' # Berjalan setiap hari Senin jam 02:00
  workflow_dispatch:

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Install .NET MAUI Workloads
        run: |
          dotnet workload update
          dotnet workload install maui-android

      - name: Install dotnet-outdated tool
        run: dotnet tool install -g dotnet-outdated-tool

      - name: Update NuGet Packages in csproj
        run: dotnet-outdated ./AumoFinance.csproj -u

      - name: Restore & Verify Build
        run: dotnet restore ./AumoFinance.csproj

      - name: Create Pull Request for Updated Packages
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: "chore(deps): update nuget packages in AumoFinance.csproj"
          title: "chore(deps): Auto-update NuGet Dependencies"
          body: "Workflow otomatis telah memperbarui paket NuGet pada `AumoFinance.csproj` ke versi terbaru."
          branch: "auto-update-nuget"
          delete-branch: true
